name: Cardgen  Builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Mono prerequisites1
      run: sudo apt install gnupg ca-certificates
    - name: Install Mono Prerequisites2
      run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - name: Install Mono Prerequisites3
      run: echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
    - name: Update APT
      run: sudo apt update
    - name: Install Mono
      run: sudo apt install mono-complete
    - name: Install mono-vbnc
      run: sudo apt install mono-vbnc
    - name: Build
      run: vbnc Bot.VB
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: cardgen
        path: Bot.exe
